CREATE TYPE "public"."journal_event_type" AS ENUM('receipt', 'anchor', 'parse_failed', 'retention_expiry', 'object_erased', 'legal_hold_set');--> statement-breakpoint
CREATE TABLE "deployment_identity" (
	"id" integer PRIMARY KEY DEFAULT 1 NOT NULL,
	"deployment_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "deployment_identity_single_row" CHECK ("deployment_identity"."id" = 1)
);
--> statement-breakpoint
CREATE TABLE "journal_ledger" (
	"chain_scope_id" uuid NOT NULL,
	"seq" bigint NOT NULL,
	"received_at" timestamp with time zone NOT NULL,
	"event_type" "journal_event_type" NOT NULL,
	"remote_ip" text,
	"ehlo_name" text,
	"tls_version" text,
	"tls_cipher" text,
	"envelope_from" text,
	"envelope_rcpt" text[],
	"size_bytes" bigint,
	"content_sha256" "bytea",
	"duplicate_of" bigint,
	"journaling_source_id" uuid,
	"spool_txid" text,
	"event_payload" jsonb,
	"prev_chain_hash" "bytea" NOT NULL,
	"chain_hash" "bytea" NOT NULL,
	CONSTRAINT "journal_ledger_chain_scope_id_seq_pk" PRIMARY KEY("chain_scope_id","seq"),
	CONSTRAINT "journal_ledger_received_at_whole_ms" CHECK (extract(microseconds from ("journal_ledger"."received_at" at time zone 'UTC'))::bigint % 1000 = 0),
	CONSTRAINT "journal_ledger_chain_hash_len" CHECK (length("journal_ledger"."chain_hash") = 32),
	CONSTRAINT "journal_ledger_prev_chain_hash_len" CHECK (length("journal_ledger"."prev_chain_hash") = 32),
	CONSTRAINT "journal_ledger_content_sha256_len" CHECK ("journal_ledger"."content_sha256" is null or length("journal_ledger"."content_sha256") = 32),
	CONSTRAINT "journal_ledger_seq_nonnegative" CHECK ("journal_ledger"."seq" >= 0),
	CONSTRAINT "journal_ledger_duplicate_of_precedes" CHECK ("journal_ledger"."duplicate_of" is null or "journal_ledger"."duplicate_of" < "journal_ledger"."seq")
);
--> statement-breakpoint
ALTER TABLE "journal_ledger" ADD CONSTRAINT "journal_ledger_chain_scope_id_ingestion_sources_id_fk" FOREIGN KEY ("chain_scope_id") REFERENCES "public"."ingestion_sources"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "journal_ledger" ADD CONSTRAINT "journal_ledger_duplicate_of_fk" FOREIGN KEY ("chain_scope_id","duplicate_of") REFERENCES "public"."journal_ledger"("chain_scope_id","seq") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "journal_ledger_spool_txid_idx" ON "journal_ledger" USING btree ("spool_txid");--> statement-breakpoint
CREATE INDEX "journal_ledger_source_received_idx" ON "journal_ledger" USING btree ("journaling_source_id","received_at");--> statement-breakpoint
-- Everything above this line is generated by drizzle-kit. The statement below was added by hand
-- (JR-204, ADR-006 section 4.2) because drizzle-kit generates schema and not data, while this row
-- has to exist before the first chain is ever written: `deployment_id` is part of every chain's
-- genesis hash.
--
-- Created here rather than by application code for three reasons: no race between two starting
-- processes, no code path that could create a *second* identity, and it also runs in
-- docker/docker-entrypoint.sh, which executes `pnpm db:migrate` before the app boots.
--
-- `gen_random_uuid()` is built into PostgreSQL 13 and later; no pgcrypto extension is required.
-- `ON CONFLICT DO NOTHING` is deliberate: if this migration is ever replayed against a database
-- that already has the row, it must keep the existing identity rather than mint a new one, because
-- a changed `deployment_id` invalidates every chain in the installation.
INSERT INTO "deployment_identity" ("id", "deployment_id") VALUES (1, gen_random_uuid()) ON CONFLICT ("id") DO NOTHING;