/**
 * Recipient-address comparison for the SMTP ingress recipient ACL (`JR-4-05b`, RFC section 4.3,
 * skill `journal-ledger` section 2 -- "Recipient not a configured journal address" ⇒ `550 5.1.1`).
 *
 * ---------------------------------------------------------------------------------------------
 * The comparison decision, and why
 * ---------------------------------------------------------------------------------------------
 * RFC 5321's domain part is unambiguously case-insensitive. The local part is not -- section 2.4:
 * "the local-part MUST be interpreted and assigned no significance by hosts other than the one
 * responsible for the mailbox." Taken literally, this receiver would have to compare the local
 * part byte-for-byte.
 *
 * That reading does not fit this operator's actual situation, so this module folds the whole
 * address, local part included: `journaling_sources.routing_address` is **generated by this
 * product itself** at source-creation time (`journal-<uuid>@<domain>` -- see
 * `packages/backend/src/database/schema/journaling-sources.ts` and its seed helper), never typed
 * by a human and never chosen by whoever configures the sending side (the operator pastes the
 * value this system produced into Exchange's journal rule). There is no legitimate scenario in
 * which a case-sensitive local part protects anything here -- there is no second mailbox
 * differing only by the case of `journal-<uuid>`, because nothing but this system ever mints that
 * string -- while a case-sensitive comparison actively creates an outage risk: an operator or a
 * mail system that happens to re-case the local part in transit (not unheard of; some gateways
 * lower-case envelope addresses) would otherwise turn a working journal endpoint into a silent
 * `550` for every message. Case-folding the whole address is the same posture almost every
 * real-world MTA already takes in practice, so it also matches what an operator observing other
 * mail systems would expect.
 *
 * ---------------------------------------------------------------------------------------------
 * Deliberately not handled here, and why each is safe to leave unhandled
 * ---------------------------------------------------------------------------------------------
 *  - **`postmaster`.** RFC 5321 section 4.5.1 requires a server to accept `RCPT TO:<postmaster>`
 *    (no domain) as deliverable locally. This receiver does **not** implement that exemption --
 *    deliberately: it is not a general-purpose mail recipient, it is a journal endpoint with a
 *    closed, operator-configured set of valid addresses (skill section 10, "no catch-all"), and
 *    special-casing `postmaster` would be exactly a catch-all for one specific address. An
 *    unconfigured `postmaster` is rejected `550 5.1.1` like any other unconfigured address. This is
 *    a known, intentional RFC deviation, not an oversight.
 *  - **Comments or parenthesised text inside the angle brackets** (e.g. `<user@example.com
 *    (comment)>`). RFC 5321's `Mailbox` grammar (section 4.1.2) has no comment production --
 *    comments are an RFC 5322 *header* construct, not part of the envelope path -- so a
 *    strictly-conforming client never sends one. This function does not parse or strip any such
 *    text; whatever a client places between `<` and `>` is compared as-is (after case-folding and
 *    trimming), so a non-conforming client that includes one simply fails to match any configured
 *    `routing_address` and is rejected `550`, exactly the safe outcome for unrecognised input --
 *    never a partial or fuzzy match that could be tricked into matching something it should not.
 *  - **Full Unicode case-folding (`SMTPUTF8`).** `routing_address` is always ASCII (generated by
 *    this system, see above), so a `toLowerCase()` call is sufficient for every real value this
 *    receiver will ever compare against. A non-ASCII `RCPT TO` address folds through the JS
 *    engine's built-in (not full Unicode) case-folding, which can only make an already-impossible
 *    match (no configured address is ever non-ASCII) fail the same way it already would.
 *
 * ---------------------------------------------------------------------------------------------
 * An empty local part or empty address (`RCPT TO:<>`)
 * ---------------------------------------------------------------------------------------------
 * Normalises to the empty string. No special case is needed: `journaling_sources.routing_address`
 * is `NOT NULL` and always generated with a non-empty local part, so the empty string can never be
 * a configured address either -- it simply fails to match, `550 5.1.1`, the same as any other
 * unconfigured recipient.
 */

/** Fold a `RCPT TO`/`routing_address` value into the shape used for comparison: trimmed, whole
 * address lower-cased. See this module's doc comment for the reasoning behind case-folding the
 * local part too, and for the cases deliberately left unhandled. */
export function normalizeJournalRecipient(rawAddress: string): string {
	return rawAddress.trim().toLowerCase();
}
